name: iOS 18.2 Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build iOS 18.2 IPA and Upload Artifact
    runs-on: macos-latest

    steps:          
      - uses: maxim-lobanov/setup-xcode@v1
        with:
           xcode-version: latest-stable
           
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo "Using default scheme: $default"

      - name: Select iOS 18.2 Simulator
        run: |
          # Find an available iPhone simulator running iOS 18.2
          device=$(xcrun xctrace list devices 2>&1 | grep -E 'iPhone.*\(18\.2\)' | head -1 | awk -F ' \\(' '{print $1}' | sed -e "s/ Simulator$//")
          echo "Selected device: $device"
          echo "SIMULATOR_DEVICE=$device" >> $GITHUB_ENV

      - name: Build and Archive
        env:
          scheme: ${{ 'default' }}
          platform: "iOS"
          ARCHIVE_PATH: "build/App.xcarchive"
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          
          xcodebuild clean archive \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH" \
            -destination "generic/platform=iOS"

      - name: Export IPA
        env:
          EXPORT_PATH: "build/output"
          EXPORT_OPTIONS_PLIST: "./ExportOptions.plist"
        run: |
          xcodebuild -exportArchive \
            -archivePath "build/App.xcarchive" \
            -exportPath "$EXPORT_PATH" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST"

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-18.2-App
          path: build/output/*.ipa
          retention-days: 7
